package resourcenames

const (
	Auth                   = "auth"
	TokenCreate            = "tokenCreate"
	TokenRefresh           = "tokenRefresh"
	TokenByCreds           = "tokenByCreds"
	ApiInfo                = "apiInfo"
	ClusterInfo            = "apiInfoCluster"
	PutConfig              = "putConfig"
	GetConfig              = "getConfig"
	DeleteConfig           = "deleteConfig"
	PutDevice              = "putDevice"
	GetDevice              = "getDevice"
	ListDevices            = "listDevices"
	DeleteDevice           = "deleteDevice"
	InsertCommand          = "insertCommand"
	ListCommands           = "listCommands"
	UpdateCommand          = "updateCommand"
	InsertNotification     = "insertNotification"
	ListNotifications      = "listNotifications"
	SubscribeCommands      = "subscribeCommands"
	SubscribeNotifications = "subscribeNotifications"
	InsertNetwork          = "insertNetwork"
	DeleteNetwork          = "deleteNetwork"
	UpdateNetwork          = "updateNetwork"
	GetNetwork             = "getNetwork"
	ListNetworks           = "listNetworks"
	InsertDeviceType       = "insertDeviceType"
	UpdateDeviceType       = "updateDeviceType"
	DeleteDeviceType       = "deleteDeviceType"
	GetDeviceType          = "getDeviceType"
	ListDeviceTypes        = "listDeviceTypes"
	CreateUser             = "createUser"
	DeleteUser             = "deleteUser"
	GetUser                = "getUser"
	GetCurrentUser         = "getCurrentUser"
	ListUsers              = "listUsers"
	UpdateUser             = "updateUser"
	AssignNetwork          = "assignNetwork"
	UnassignNetwork        = "unassignNetwork"
	AssignDeviceType       = "assignDeviceType"
	UnassignDeviceType     = "unassignDeviceType"
	GetUserDeviceTypes     = "getUserDeviceTypes"
	AllowAllDeviceTypes    = "allowAllDeviceTypes"
	DisallowAllDeviceTypes = "disallowAllDeviceTypes"
)
